name: deployment

on:
  push:
    branches:
      - user/*

jobs:
  install-terraform:
    name: Install Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.4
