#ENC[AES256_GCM,data:7Fnsp1e4kraDrMG2fPFff6z4,iv:63385rv+apoRMJ34dQDBU/3hX0ft69Afmb4DsBMhkio=,tag:WxS32K7X/ijxVa7pXya10A==,type:comment]
#ENC[AES256_GCM,data:3JrUcPHiNC1OwPx5HAT2kCJt8pJ257gqZEItaOS+vwaXy1xsCYVHg/ZXDP60+PUl,iv:ovSDwb10PgpjsEgQUjKcBrN3KPcF6o6u9i3kTfH7k2E=,tag:GnTWD9OsuP1bzYHlEd6udA==,type:comment]
api_region: ENC[AES256_GCM,data:0oFhQ8cw44y8,iv:z9Rm1Z3N4ebnkwcz4aV3ikCKYU+8x8DH0JIQ5wlg6XY=,tag:tR/ZXRB3hAU3WaGT1WLn3Q==,type:str]
#ENC[AES256_GCM,data:62vA35rk+ZenjIsFeL9vaxEdCnA=,iv:j/xsgm2pGJlHoWXFejNwL04ChyuSlW4ovLlgbG2Ap/M=,tag:9i0kpm5I9hVfIic1HFTvZA==,type:comment]
account: ENC[AES256_GCM,data:oiZrg9cWfOAmxzCq,iv:xu6NeJdr1PDEgZ6SKqpi0vKENK6HNZAzwNlwAEyBg/4=,tag:fJ1iyeC7Bnp93KZW8UvfHg==,type:str]
#ENC[AES256_GCM,data:MqGhwC+gPE8+Hfz0ORSB8Hwa8R71KBcOV0cyLHNqgH389/BNnKd2CrjTpTfI/A==,iv:jKwMbkdFiyGGszIYqfIab8Ea6rLqvLuXKofMFmzFJ8s=,tag:ycrHZIv5ml6wrkbSRetSCQ==,type:comment]
bucket_name: ENC[AES256_GCM,data:GW4hckBJRNYkCT2pMxbdRlkCKg==,iv:CytNE9p6lK08xiWABQNMIXyT/NEiXu0/X64biyXmDNI=,tag:JMIhGtCsHxGFE7s5JUOteA==,type:str]
#ENC[AES256_GCM,data:krNDPN/dC34gLleZ3z2i90nILrEcYKhKhhIkdquihEQ+FclqFA17G24insFqFsXeZZ2GihzNqQ==,iv:MsuiYh/axIDawb+TMUijX+8I74UAzovnnMAvcYERxMU=,tag:s9MsFDQx56+xp+XQ6keOHQ==,type:comment]
ses_sender_email: ENC[AES256_GCM,data:fmpKEYOMTewWwwFGN0iFuaxpK0WF6qm9dIpWkuM/2A==,iv:r3u++bealMwzWFuz8A0xtBI+BNwXNhNG6U+ECOXYfxw=,tag:0LygPFqIH+gJyKQNKOHWHw==,type:str]
#ENC[AES256_GCM,data:W726ZLs4ziqlQfuPTd+XTo2s9ujar+VQGt6UvsyfPktX017R7yJIL33gxLiOyT8=,iv:8vF4wjkFvA81Hyq9nFBJJhCxpn6/BZ+czhCr8ZT+pqw=,tag:JcMyZxRfwbdBuLXAOq8h5Q==,type:comment]
domain: ENC[AES256_GCM,data:ZHfqLuHEBqBd9w==,iv:TbLi1N9FwXBH5Y+lvEOEYgwef99+HwIrVL+bO/y6QJU=,tag:63ekIxFjh+m1dzzT0HsvPA==,type:str]
#ENC[AES256_GCM,data:Elp2E8yW1nLegDAh1Oq8mYzprHvyi1D2Ew==,iv:m6JoEEK0yt7ngYnNBBNM0j4p5kByN9r+W2IguewKKyY=,tag:SzkKZvNAOPw5TGcG9BYQcg==,type:comment]
#ENC[AES256_GCM,data:20EzconRm+dRlI/60BfAm2JicL3ihjYF,iv:j1CGwMN1wCQPOXf182L0l7u45atI+8LIOpB4ocfFczM=,tag:F7e2FazN4N1qMVjpLkD+sQ==,type:comment]
name: ENC[AES256_GCM,data:X1S8AQqUYu5t,iv:azrx1k+K8WBAD95z6lkyo96W/csrziuQaLimqjw1nac=,tag:AV3g5+jJEigFENcrO2yEKA==,type:str]
#ENC[AES256_GCM,data:wJhHG+jZQdhZ2yaphwv4dwlF5BBraBQI+KC9I8ZLKmNbbUo=,iv:JFbT+meVNsaOPCXVJ8VhIt8Mvc01jnf2sYAHUOqV0Do=,tag:m9VClld+9xfEEm4HXd3AxA==,type:comment]
image: ENC[AES256_GCM,data:5kKEmGh/oND+/sdCjmlY,iv:ATn99eMwTMpYux0cMx4WlYOU69yE0HVWANo0eq+CYbs=,tag:ZnJhgO7uch5wDd17Bo6CBQ==,type:str]
#ENC[AES256_GCM,data:lkVkpDr0JiHj3vhzVIzunt/NTDOk,iv:hsukVUinWfQjwJF1DQuZ7Aoy7fpLWIgN0t/qrMJyteY=,tag:Q2IH1mxtfksxkpkiC/a/LA==,type:comment]
instance_type: ENC[AES256_GCM,data:sGeQWdtY81c=,iv:jI45yaBdb6Z+cR3YRAd4gvUUV753CgXqoSzFTIBxqxs=,tag:aL0HW+yb/bpxLdiTBEFqsg==,type:str]
#ENC[AES256_GCM,data:9Ppbsqp3uVaoa0/jAk3kKmFLFLYCgJYWSSZWZw6u5UdrjWPmKYkCnJTIbmalCis6qmyT1uCOg9c=,iv:6Zqjs3/ulnGenWc0L7cRwvcY1ZSBKQojM5Q9TYg7MHg=,tag:3YbopwLFXyjrQbZY7kBzHw==,type:comment]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2023-10-04T22:27:53Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgFAUh29Xr08+/WOGnXVvJWVAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM+6qhNQxlUsZIE5R3AgEQgDuk8GR8o28RI4kv65kVIBHUptslCY65UjECiIzCuMq6y5QpAPmqisw7WUrJ8nBQMAwnGKYNoMvqWWxajA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-04T22:27:54Z"
    mac: ENC[AES256_GCM,data:X6HJJGtKqrT6ApXevHW+3oSyL1wddTB7xhwZDg7eeGoy9qlXEWhHVxRiahPavtlB12uxDyPqiq5GT1BnLUvd2tDtHTu3K4IRGHnNCbtvFDzSyB0ygAQ4NtEWDIAqNhQc+Z/zmuaCTxHkb7ztgDUwMygYvX11GhSn5+/nLGfdsbk=,iv:/dYqw/0qjK3Q4yDBi13vSovzxuipkU/b8PXA71km258=,tag:fpDI4/wlUzjjdtlWFZB0mg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
