#ENC[AES256_GCM,data:eZKmhgqrUnIsIG5xLtnB3Wr6,iv:SPfX9lHTQhs2WVSLstvB1SNG7i9WhsfMarz0qJIH5Y0=,tag:WkTotBJcgaJP4s1Zg/cdRw==,type:comment]
#ENC[AES256_GCM,data:i2NHsLEy0MevuAQKsTXAiVlEg62K0c1QCEJThpwiOXpA3wzKPSFW2pp+0N9hPedH,iv:WN6+E900ZhsFe7V9VTLLWep+auQHkrqr1JGTzKXKCkE=,tag:jg8gWJpSZgPlF3QVKkCxew==,type:comment]
api_region: ENC[AES256_GCM,data:aEIEElwzjIpK,iv:Hg23BANTd5mkaiH+7fXskh/NqdBsSv8yVp+suM8lAU8=,tag:8WoDDZon3WonHxuVbTlNaQ==,type:str]
#ENC[AES256_GCM,data:5WIg9QwIhD5UIvIv/0QBzoccd0LunEn6yAPya7f1wx3SmSSHBS1F5w8bzWavqw==,iv:dE3RLZt+kDsrG33ESsWdb31ndmNGbSdGcXLyN/SwnEA=,tag:SgJ83Ht7ivPLFVe648bh6A==,type:comment]
bucket_name: ENC[AES256_GCM,data:52g2TN0NcIZlesL5O5OW5i98fQ==,iv:aNkWQEolRlH1w/mu1u0m4UYAfJZzCcSpjnTZ3mI6MYc=,tag:iYIAIMwBFuUXzfbn0SPCkA==,type:str]
#ENC[AES256_GCM,data:LbPpYttsZFGS2tlZgxVQJ5FypPZBEcIsUhhOLIdGHf+abAn26C0ONNTFOrMDGHMfT6zraJtOGw==,iv:rl7Y2uAuBHIXi+a8EUaTGQVAjv9rqxTUkVLFH7kvRNc=,tag:Rdhl9WLO2d6PPbrSat+7IQ==,type:comment]
ses_sender_email: ENC[AES256_GCM,data:YKNcsVQOgR61JLJ06H0zhBE5,iv:rGcplQRWejlUr1pf/kIN8mb9adDTq3UWHSrpRlXnsLM=,tag:wu1yUpZJYcWNgcYZV+3EkA==,type:str]
#ENC[AES256_GCM,data:qj20P4Dy/xx1jXoF18pCVVwVTrJxwHIboFMaYx94u2+vC5oqNZw4UwiMZVgvB0I=,iv:bLkMJvDYDH9qa+QjuX9Ptuh8C/niLhA3H2ADsZCJkbI=,tag:wJMv4KkG+pPypyH2VCn5Xg==,type:comment]
domain: ENC[AES256_GCM,data:6ACEQR7bjnfSvA==,iv:IczyB/qwomu6uwPu5Wjk/DiwiTc7bqCsaQeUL5OdxIs=,tag:maI09jIwAhkqmjF1buoBjA==,type:str]
#ENC[AES256_GCM,data:MULnmfmsN1tup/ZbKlpsOvUflSzZyVdNwQ==,iv:N6D6/Cf0HTg3RQfLAVOLwskcG+eqk5MYeFJ1dpZ+P+M=,tag:qxp8mtfjbP+8RJk5j2yu1g==,type:comment]
#ENC[AES256_GCM,data:92iWz4Mtjkz/+0vySvQKJdX33TKnDkEn,iv:RkidzhDJZj72TDzttEqYLXoMlWe9dt6PLJfGdYXvNgk=,tag:lH44bp07L5Cc0LdQ9TQ63A==,type:comment]
name: ENC[AES256_GCM,data:kaujzGSmeg9+,iv:5n+nUzngVtMRKYe//QEzMaA0OHT6PgrFqtinDa8b6tw=,tag:oCCtvR29CSxkmglPWcRi9w==,type:str]
#ENC[AES256_GCM,data:WDlFt5rB/JI8R0PO2LDQ5HCdXcmhD7aTjCi+5OtMarO3z3g=,iv:fhzKZwVGPgl3No68t8HWMzYwMLFiWVNfgn09HcuOo6w=,tag:rwntnhaG13fq6GQI1cw7WA==,type:comment]
image: ENC[AES256_GCM,data:JwnJ06ZbPqLK/V5f/Pmf,iv:/7X8kH8c+ZKIEEXtNWPCvgf6OLeFSgtLO0520e6l7GY=,tag:wJIRoOpHvI2xYsris4wIOw==,type:str]
#ENC[AES256_GCM,data:06AVt8PTbFN+PVkMbycF8OHW/HLf,iv:HDhU1tGb0mq7Y/wPvQOx93cSzr7BXYJkiqmN3+LOfcA=,tag:gY0NWztYjI5uz6WYri2rIQ==,type:comment]
instance_type: ENC[AES256_GCM,data:G4SNESeIaDs=,iv:k71pMz2h4+DGECF7URsONFYBlMIgF8MeXx3ByEy7f64=,tag:ZGPq1wsjSuEPk9Lwx5jtZQ==,type:str]
#ENC[AES256_GCM,data:YpG7ab2okPDmXVEmmdmm7pOcgl9KWbM08PTdFmTRyyDPWxRC8x3in/udK7+LMiQ50ZZvOF4tRkk=,iv:EDgD8M3Y3d67QrqMJhz09AFpf5qOysW0gkXxFCSMlNI=,tag:1B5bivOW44vcSU+M/07RsA==,type:comment]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2023-11-11T20:28:05Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgGSeim9F4a//y0NZPVk+LByAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMiAphQijrTXsBSHyIAgEQgDsqCR55rsiM9PZYuu3UTiKO9cU5YOzptfhQFZA7nsd4bUImkrnjqWJhxE1faLRpiwWWF0f34YcoFTphEg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-11-11T20:28:05Z"
    mac: ENC[AES256_GCM,data:9yg+dQqpdPqHpsFcLhKTROznwrS0Y14vsMwkafjRXn4XFw5FekxaJQ3YiBhogWhUZBOpIGeiXTa2DDDjgGqyMU1/sQo+VYXlFWd5PSVXrhSrLvZLXJX27CfrcYerntnzYMILQwsVSoHXvfo4uPWTRYaU5iXiUGurZk/ZlIYBfgQ=,iv:ePyke6Trv8TPOfcMNU3KaBVX63YV3O0mbFYt01NlsOw=,tag:Ktn05DXz3xpxPq6q0DfWyg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
