name: "ninja-vpn"                   # Name for your resources
region: "eu-west-3"                 # Choose an AWS region 
image: "al2023-ami-2023"            # Amazon Linux 2023 (Default x86_64)
instance_type: "t2.micro"           # Around $0,13 per 24h
my_timezone: "Europe/Madrid"        # Choose your timezone
email: "example@example.com"        # Email to send the connection details
countdown: "5 minutes"              # Countdown to terminate the instance (Optional)

# Available regions are:

# us-east-2 (Ohio)
# us-east-1 (N. Virginia)
# us-west-1 (N. California)
# us-west-2 (Oregon)
# ap-east-1 (Hong Kong)
# ap-south-1 (Mumbai)
# ap-northeast-3 (Osaka-Local)
# ap-northeast-2 (Seoul)
# ap-southeast-1 (Singapore)
# ap-southeast-2 (Sydney)
# ap-northeast-1 (Tokyo)
# ca-central-1 (Central)
# eu-central-1 (Frankfurt)
# eu-west-1 (Ireland)
# eu-west-2 (London)
# eu-west-3 (Paris)
# eu-north-1 (Stockholm)
# sa-east-1 (São Paulo)