#ENC[AES256_GCM,data:G+GhBM1kOp/lcRyBJV3b6ZrS,iv:QdlmGyJmWaen+RBp2YwPxue+ZrqRs9cvOl+7tVuayls=,tag:ifVdSter9LQA75jX8xxubg==,type:comment]
#ENC[AES256_GCM,data:+8XDpghG8mvb3YYsRzt2LiX679DM8ATI05gQ/PAYpLY6LNmPshGo8dS/SIgo2GR/,iv:TcDAjU4GJo3KcnpcBpIK7Ba049WQXUrI3W9KDWfWpTY=,tag:7aKhPBXtmhYb3WBYnxQQig==,type:comment]
api_region: ENC[AES256_GCM,data:fjgIiImgekXj,iv:ae/NNoqTo6SSY/r9Kw2IdUnGzHmGXbX2Fh0ZoSCF9a8=,tag:kMkkGt/hhewxjZTxl3z1jw==,type:str]
#ENC[AES256_GCM,data:qqv+HJEXJumwZM/Y,iv:JQ1dxVWheSv7iAbKM0i38jTeyq03yEH0c6ZeZLfz43o=,tag:TlcEvtczQCzwVCeIKBvFvA==,type:comment]
aws_account: ENC[AES256_GCM,data:PT7RnwHabjZcU5ci,iv:ZwXSBW22QmZCSR5amQKwiGvob5PZ4s5dRR0h0nYbU1o=,tag:1D34uDMs8isxyDgOKtkKsw==,type:int]
#ENC[AES256_GCM,data:srIHBlz75RFcPflv8S1SzUBi/szmCtMspbOkNo4kyhNTPcfzNvY+P+wob/R/ig==,iv:wHbCWDa/2kPnBneQlKBRL4G9CNXwNKh+HVV2Gs/ykCA=,tag:1Rel4Y6uQreADR/d0fGa9w==,type:comment]
bucket_name: ENC[AES256_GCM,data:I2fgdXUGid0cjUeuBcoF4vosJw==,iv:NdjilSvnsEDg4qEAoJ12VnipyHI2Vvuthlo8BpI4t+c=,tag:4qPjZPROLgs9MMzP+uHaIA==,type:str]
#ENC[AES256_GCM,data:H+GZ6ppJ4EQ+HyRYqAn1kFLOjnFQJu6NwbAXRDA6Ohlfrdke89MRlISGKMFDhxJwjohSpK0JUA==,iv:YaNKb7GVbdsa9WLMgTWUJbS6PNBQLsUnH3QgQBfp2m0=,tag:24BiGRQqQL0GuaBePPcX3g==,type:comment]
ses_sender_email: ENC[AES256_GCM,data:6QIaU/BquIm/6uGJWIa0foxd,iv:lNSl3sHiPYrks+ZD0jiHaPv7M3yhkxmsmExWnMtIYWY=,tag:7jxI+RChnDcyXXoQwYn4Bg==,type:str]
#ENC[AES256_GCM,data:doM9gn2QPMv8cQj5AsBBBf3ToEsx06TOsDtbT32lG1IgvzqhdpSBmRm4Fu99wWg=,iv:vphH+HNLTFhLnIUP0dzvcqeKGATlTgnw/ykwH+0k9cI=,tag:F0BtdZwDLTzKyvNKydyKJA==,type:comment]
domain: ENC[AES256_GCM,data:HMi5fu+qT62QOQ==,iv:3LW2rHxiOq/MryvOdgwYqVJ2ou4YfyPIhFfRxMpd2bA=,tag:K6aGET/duTB8N7L3NaJ97Q==,type:str]
#ENC[AES256_GCM,data:PLw9K+rFZSFRrlq4b9WnEMmzh+VClecftQ==,iv:wHARBOBU88YrKemy8ZG1ml6UT8erAojMfKmzQq/5XXU=,tag:s2xaCw+gOC1UnY7NNywIgA==,type:comment]
#ENC[AES256_GCM,data:Kup319jeP2CCuosUzxBS0IwVQvl9E1sh,iv:K75vbFDXbP47L7w83H97MwHDn3Y730CQ5NazcmdRc5U=,tag:L2a6mE9pezzSAO7LWRhpHQ==,type:comment]
name: ENC[AES256_GCM,data:BCcC3Ti0rIFc,iv:pN1QW73nc+LA5eN7w5W9XDs0EFIINNVZSVJ9FhX1p7g=,tag:M20hkr6i13FiggTIUrr1oQ==,type:str]
#ENC[AES256_GCM,data:8ExfGohnJJ5wcG/RZ1t0329NbBPO2/dgbfcyaxDnYADUd1s=,iv:WWlFtT64e8hGiTWZcN5gfTzGOwzfDSFWTh/JpG1CSAg=,tag:vZAGnHqq1Fwj0GAovO8Tzg==,type:comment]
image: ENC[AES256_GCM,data:ThtEH5ABNbmmT3GJMtx7,iv:RJDLTJOIJu/FfpQNdqoGg9JVwKRbHsGZOnLahrEqSUI=,tag:11Cz8i+AOM105BR0E98dVA==,type:str]
#ENC[AES256_GCM,data:QpBxM5J0EmPY4w0pXvohwBHpJjmv,iv:q4unNxCo1vBTlEx6V3UL2qpRUBADMr/343GnEKSDLRQ=,tag:Fg9wx5Iyu/yyPcs7YMoJOA==,type:comment]
instance_type: ENC[AES256_GCM,data:S3OFY1QTERY=,iv:W9JXkiLynXZIZvViT6PJd9uiOgT8nRVphseXg7Sfo78=,tag:d7NmBp/HkDrr9zSzpvMX+w==,type:str]
#ENC[AES256_GCM,data:N4sikqWKWZPNgyZIXdjqk8qFWvxMy6PAbUPv4DZl+fghZwhbSU9P/npYKpsze1h10EFsLey5vyA=,iv:EqinCr2zw3oa42z0EDDjAlnqT9e+NTvCyd41+jh7Mig=,tag:W7JSsPl1WyIuYICl/avq6Q==,type:comment]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2024-02-10T16:15:49Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgEpN85dudx9CdaKrXpGu61bAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMUS7g78gYG5rcG1WRAgEQgDvwUINmZR4DX8jDvGAovhBzujwMS6PR1xgNGVUyY4pgMEjl0J7YhuZMiQUYF6a0QIjzeYjnrHjjhL0ErA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-02-10T16:15:49Z"
    mac: ENC[AES256_GCM,data:8Dop1FngliigWvvHzoQr3tUX9jxnO8huqfY4rkoi63puxvVW/kWy1OwuVpsXiQTK0aqKiM3WybcRb/zUl9t/paoF1Xl4qsW6yxyc3zp758kTB0c7nnBFIyhJDOKIUfSesvPCmurZVmJyvfSEuUYO4owp9YIcIzjbXW364IuDCMU=,iv:WZPXhf2W5lPmV7j/AI/Fx+EbMYiZX8qXxxpM0bUpHeA=,tag:TGqk/3xjCcBnLo2FqrK5Iw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
