#ENC[AES256_GCM,data:5U+063oWsN7MYUva1VjNPwo9,iv:jWajtVLJfQk/fHsz3qC1NQc5YPumTd7HrmZChagVo0w=,tag:VDdJ1zmvwSWQAwCcDexCDw==,type:comment]
#ENC[AES256_GCM,data:fccihhXevvqE188lB6zGjKIx/d4aUQwXsg7vePaRAhMHakIIKW8+ORovLUmx7jdE,iv:FK7fYqSWysPp2fEOjYJe7XIwE57sF0vCimNPXd2gM6I=,tag:YVWD1mEoYABr+Mbw9DU+bg==,type:comment]
api_region: ENC[AES256_GCM,data:v6TIjB/HfM8g,iv:AeJouxl3OLBXf9wG5goVB/SEKPAiT2VFR0LWtA3Gxkw=,tag:NArJDlHyx+anXQKhCOBbYA==,type:str]
#ENC[AES256_GCM,data:ChTM3XqAzGnX+3cGy1BYFmpDeoE=,iv:4ESYHFjuImvZx1nTgKyfvsBKzS/tQLiwqRvJKc2jd1g=,tag:+6lOWQNHYTLXfzKXfBb/dw==,type:comment]
account: ENC[AES256_GCM,data:g1OlBgE4v4GYskWv,iv:zkjM5oibWZXo4ID06+7RzKczacKHSg1du0jbxThlTlc=,tag:TYqGQliuATR0xULg3nynDw==,type:str]
#ENC[AES256_GCM,data:1iT1ELgTnoC03zEahsgW7MOZsfhj3cMORJgmMA/UEFxfl3B5ULHxIzLTLwyqBA==,iv:WclmM9wv+byUmEkNyeisYp7kJ+NYGSTUNrYvEWnjvHk=,tag:+eSPZsO3YGxr5Fu/TeTsRw==,type:comment]
bucket_name: ENC[AES256_GCM,data:fEUY2rdsovU3BykCk3OCd5c/LQ==,iv:mCLjqEdJivFW0SUWDwCz75qfwTO5BRkmqNZYTKrEtr0=,tag:PRGVUWkuaIr959Y7fkhUzA==,type:str]
#ENC[AES256_GCM,data:OgC/InG5pwCT6AgLuC9vsU0KXZOka2QzP+bM8Oty5PyyppiQpKyzkFxz+OJjSKhPF8b3WnJqLQ==,iv:FbKrIjWWq98vBj98cOYl6PUVFm6OQYJSjmNvS/D8Gy8=,tag:0D70s54FT3HpSETriKYm+A==,type:comment]
ses_sender_email: ENC[AES256_GCM,data:lT4MJJYSiDixi0QwmvSwXEgF8maY4tupbqqen2Z/1Q==,iv:iEr6F2eOn1mUgPiXEpj0jwo+SrK+X4gU6XcyPD9ah/w=,tag:OrQZD2wBtJmodBjwar+OsA==,type:str]
#ENC[AES256_GCM,data:NiaFdQ1QE1wGEboNpxCEKJtI3z5IDVw5MA==,iv:iPX7pot36ctPM2zcEsBE1RIardaozbiN0YBKiEW8Hfk=,tag:MCHz4bIcsSRqHficfZyqXA==,type:comment]
#ENC[AES256_GCM,data:78f1H68VVUjRjRQ16dxdy0O/359aVIZl,iv:ahoKhnFSnxX9ro8rRE7na4xM2AhYUNte/oyb/7FFJkM=,tag:WwhICD20hENuo7dZRGY0hA==,type:comment]
name: ENC[AES256_GCM,data:jCthE+D0oiZA,iv:e3iwy2VNUuVklkpFfwHH6C+K6LTQF80VaryX4F4CYaA=,tag:iQeRjbJjyChF9i05RThrzA==,type:str]
#ENC[AES256_GCM,data:8cioiDj0Ktakm340PJzeR4qNC7Ekb0uATbLbur+H9WFlv7c=,iv:7bXOcF+go6y7Efaxnx/AC2Iv8elISmOndyBoL1Qwpgs=,tag:/8tc/1k1zJ7A0lsXVK86XQ==,type:comment]
image: ENC[AES256_GCM,data:0z8y9n6mnD3Kstd9CRWk,iv:rBjGsZw2iQCA0CY2HYQ/YZzeFLKNQXu8HkmFZSkxAKo=,tag:JHbd34iNn5TYsj5FQd4UTA==,type:str]
#ENC[AES256_GCM,data:UYzBqG8rwN1wCXE+b9G1hvlyh3JF,iv:p+G0UcAKrmZaThx+Ukdty9dPa13wz7Ihb3Jtc4Ex0Pc=,tag:rgZO5oPLmZ6BMqM1Wjs9Tg==,type:comment]
instance_type: ENC[AES256_GCM,data:M58AhifjGnI=,iv:BWBHh27hWuyDdFCvjPH3bGKNafjAPyWczjwa/JWyPU0=,tag:InPofb+AReKNmYcdT9LM7A==,type:str]
#ENC[AES256_GCM,data:J4/bhllnLcBcR8WuYOSsQU3KeumG7hZAB8pF6ssSYJETwCScgqJ0jL8OSbNm8kdtacJhYCzvML0=,iv:aJhCuKH3JXUSJqQ35HdYLFcwS3ONehaedrYkAvEfQbc=,tag:YYK/4IxN4/U2hh+3t7nmEQ==,type:comment]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2023-09-24T09:15:27Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgE0QZ1JKip22KTKex/ltpgAAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMtUXRfkVkhu1j26LvAgEQgDuyDpOj7v78CSbZ9h1eYqquFwXDC7VRzUk6Z+9LLC9GxAJxoWYs26e6xb2qd6t9wYrnUA8EnO9VEMWbjw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-09-24T09:15:27Z"
    mac: ENC[AES256_GCM,data:o+5/wLkCIWVcsl81p2naC+l6D6KR+xmjIa2uOgFCc5gdd5dgjgyc5CksBaozkJKFx9WKOpjyx/5NoWnx2YJwAV0qDHJR+vfxQHi+0KHgo3GiEdnmEBSU3lJ89kNeDggjIh8s7aLDsEl4ePZpIt10F6ob1IlxLd2uNLsc2/QdPFo=,iv:cQLBx6fkQ6NQrJV+OP6OUcrSTPMbXbyNOclNCDtcVvY=,tag:F4MT3FRtB6JoTwS3jVkDmg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
