name: deployment

on:
  push:
    branches:
      - user/*

jobs:

  install-terraform:
    name: Install Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Testing defautl vars
        run: echo ${GITHUB_HEAD_REF}
      # - name: Set up AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1
      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v2
      #   with:
      #     terraform_version: 1.4.4
      # - name: Terraform Deploy
      #   run: make vpn-deploy USER=
